banner:
  enable: true
  title: é˜¿ä¹çš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# å…¬å‘Šé…ç½®
notice:
  enable: true
  content: Thanks for playing my game.

# ç›¸å†Œ
albums:
  enable: true


# ç‚¹å‡»å›¾ç‰‡æ”¾å¤§åŠŸèƒ½
medium_zoom: true

# å¤´åƒé…ç½®
#avatar:
#  enable: true
#  url: 
#  rounded: true
#  opacity: 1
#  mickey_mouse: false
#  status:
#    enable: true
#    emoji: ğŸ˜­
#    message: ä¸æƒ³ä¸Šå­¦



# ä»£ç å¤åˆ¶æŒ‰é’®
codeblock:
   copy_btn: true
   
prismjs:
   light: prism-dark
   dark: prism-funky
   
tags:
  Vue: '#4fc08d'
  Hexo: '#0E834D'
  Java: '#5298d1'
  Node.js: '#026E00'
  Git: '#F14E32'
  React: '#61dafb'
  Python: '#3776ab'
  PHP: '#8892BF'
  VS Code: '#0066B8'
  JavaScript: '#F4DF4F'
  TypeScript: '#317AC6'
  Laravel: '#F4645F'
 
# æ–‡ç« åˆ†ç±»å®šä¹‰é¢œè‰²
categories:
  ç¬”è®°: dimgray

# è¡¨æƒ…é…ç½®
head:
  js:
    async:
      # è¿™é‡Œæ˜¯ä½ ä» iconfont å¤„è·å¾—çš„å›¾æ ‡é“¾æ¥ã€‚
      iconfont: https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css
      
      
 

